### ISSUE TITLE
not getting loaded on LXD based clouds.. is it possible to test in LXD?

### ISSUE THREAD

**Issue by EMCP** [canonical/certbot-charm#15]
I am working mainly in LXD.. and only just now starting to branch into getting my charms to deploy on a public cloud.. in this case AWS.  This charm, I was hoping to test and configure using my LXD cloud.. but when I deployed it doesn't seem to grab a server.. 

```
juju deploy certbot
```

yielded the following status

```
$  juju status
Model   Controller           Cloud/Region         Version  SLA          Timestamp
mymodel  localhost-localhost  localhost/localhost  2.9.2    unsupported  19:41:06+02:00

App      Version  Status   Scale  Charm    Store     Channel  Rev  OS      Message
certbot           unknown      0  certbot  charmhub  stable     1  ubuntu  
nodejsapp         active       1  myapp   local                31  ubuntu  (update) nodejsapp is already running on 3000 : 17:39
mongodb  3.6.8    active       1  mongodb  charmhub  stable    60  ubuntu  Unit is ready
nginx             active       1  nginx    local               17  ubuntu  (update) NGINX is running 17:38

Unit         Workload  Agent  Machine  Public address  Ports                                    Message
nodejsapp/50* active    idle   54       10.1.1.1   3000/tcp                                 (update) nodejsapp is already running on 3000 : 17:39
mongodb/15*  active    idle   54       10.1.1.1   27017/tcp,27019/tcp,27021/tcp,28017/tcp  Unit is ready
nginx/18*    active    idle   54       10.1.1.1   80/tcp,443/tcp                           (update) NGINX is running 17:38

Machine  State    DNS            Inst id         Series  AZ  Message
54       started  10.1.1.1  juju-ac434c-54  focal       Running


```

Should I just not even be trying to use this charm on LXD.. or ? 

I double checked and although I will deploy the server on AWS.. my DNS provider is google.. perhaps I need to provide the config for it to even start up?

**Comment by EMCP** [comment]
after having played with certbot manually.. I am perhaps realizing that the working assumption for most users of certbot is that this runs on your own server hosting the site itself.. therefore does the charm assume you're going to add ` --to 54` ?

**Comment by mhilton** [comment]
Hi @EMCP,

The certbot charm is a subordinate, so it is expected to be used in partnership with another charm, such as haproxy or apache2. Subordinate charms are deployed on the machines (or indeed LXD containers) that are running the primary charm that the subordinate is related to.

To deploy the charm you want to do something like:

```
juju deploy haproxy
juju deploy certbot
juju add-relation haproxy certbot
```

**Comment by EMCP** [comment]
im using nginx so I will give that a shot.  thanks!
